<?php

/*
 * DO NOT EDIT THIS FILE MANUALLY.
 * If you want to contribute to translation, you must instead use the 
 * SimpleSAMLphp translation portal:
 * https://translation.rnd.feide.no/index.php?aid=simplesamlphp
 *
 * This file is automatically generated from the translation portal.
 */

$lang = array(
	'yes' => array (
		'en' => 'Yes, save credentials',
		'de' => 'Ja, Zugangsdaten einrichten',
	),
	'no' => array (
		'en' => 'No, cancel',
		'de' => 'Nein, Zugangsdaten nicht einrichten',
	),
	'sgis_header' => array (
		'en' => 'Set login credentials for SGIS',
		'de' => 'Zugangsdaten für SGIS einrichten',
	),
	'sgis_accept' => array (
		'en' => 'Hi NAME (EMAIL),<br/><br/>set your username and password for use with SGIS.',
		'de' => 'Hallo NAME (EMAIL),<br/><br/>hier kannst du deine SGIS Zugangsdaten einrichten, welche auch für den Kalender, OwnCloud usw. gültig sind.',
	),
	'sgis_error_desc_fieldmissing' => array (
		'en' => 'Field is empty',
		'de' => 'Ein Feld wurde leergelassen. Bitte fülle alle Felder aus.',
	),
	'sgis_error_header_fieldmissing' => array (
		'en' => 'A field was empty. You have to fill all fields.',
		'de' => 'Ein Feld wurde leergelassen. Bitte fülle alle Felder aus.',
	),
	'remember_password' => array (
		'en' => 'Remember my login',
		'de' => 'Dauerhaft einloggen',
	),
	'remember_source' => array (
		'en' => 'Remember my choice',
		'de' => 'Auswahl speichern',
	),

);


?>
